name: Auto Merge Documentation PRs

on:
  workflow_run:
    workflows: ["Build, Deploy and Release"]
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # só executa se o outro workflow passou
    steps:
      - uses: actions/checkout@v4

      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.workflow_run.pull_requests[0].number }} --squash --admin
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}