name: Auto Merge Documentation PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'documentation')
    steps:
      - uses: actions/checkout@v4

      - name: Merge PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = github.event.pull_request.number;
            const owner = github.event.repository.owner.login;
            const repo = github.event.repository.name;

            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number: pr_number,
              merge_method: "squash"
            });
