name: Auto Merge Documentation PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner && contains(github.head_ref, 'documentation')
    steps:
      - uses: actions/checkout@v4

      - name: Wait for required status checks
        uses: stefanzweifel/status-check@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          ref: ${{ github.head_ref }}
          checks: build
          timeout: 10m   

      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --admin
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
