name: Auto Merge Documentation PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner && contains(github.head_ref, 'documentation')
    steps:
      - uses: actions/checkout@v4


      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --admin
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
