name: Auto Merge Documentation PRs

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]' # só mergea PR do bot
    steps:
      - uses: actions/checkout@v3
      - name: Merge PR
        uses: pascalgn/automerge-action@v0.15.4
        with:
          mergeMethod: squash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
