name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Altere para sua versão do .NET

      - name: Restore dependencies
        run: dotnet restore 
        
      - name: Publish Blazor project
        run: dotnet publish -c Release -o release

      - name: Upload publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: blazor-release
          path: release/wwwroot

