name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Altere para sua versão do .NET

      - name: Restore dependencies
        run: dotnet restore ./src/Server/Server.Main.sln

      - name: Build
        run: dotnet build ./src/Server/Server.Main.sln --configuration Release --no-restore

