name: CI - Pull Request

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: write

env:
  CSPROJ_PATH: ./src/ExpForge.Documentation.Presentation/ExpForge.Documentation.Presentation.csproj

jobs:
  # =========================
  # ✅ Build e validação de PRs
  # =========================
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release --verbosity normal
        continue-on-error: true

  # =========================
  # 🤖 Auto-Merge de PRs de documentação
  # =========================
  auto-merge:
    runs-on: ubuntu-latest
    needs: build
    if: github.actor == github.repository_owner && startsWith(github.head_ref, 'documentation')
    steps:
      - name: Debug info
        run: |
          echo "✅ Auto-merge conditions met"
          echo "Event: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "PR number: ${{ github.event.pull_request.number }}"

      - uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Merge PR automatically
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --admin --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}